import NavBar from "./components/navbar";
import './index.css'

export const metadata = {
  title: 'MyPlan',
  description: 'Generated by Next.js',
}

 
export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html>
      <head lang="en"></head>
      <body>
        <div className="flex h-screen flex-col md:flex-row md:overflow-hidden">
          <div className="w-full flex-none md:w-64">
            <NavBar />
          </div>
          <div >{children}</div>
        </div>
      </body>
    </html>
  );
}