import NavBar from "./components/navbar";
import './index.css';
import { Open_Sans } from "next/font/google"; 
import { Provider } from "react-redux";
import { store } from './redux/store';

const openSans = Open_Sans({
    subsets: ["latin"],
})

export const dynamic = 'force-dynamic'

export const metadata = {
  title: 'MyPlan',
  description: 'Generated by Next.js',
}



 
export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html>
      <head lang="en"></head>
      <body>
        {/* <Provider store={store} > */}
          <div className={`flex h-screen flex-col md:flex-row md:overflow-hidden ${openSans.className}`}>
            <div className="w-full flex-none md:w-64">
              <NavBar />
            </div>
            <div >{children}</div>
        </div>
        {/* </Provider> */}
      </body>
    </html>
  );
}